- package.json
- scripts/mock_api_server.js
- scripts/modules/fagsaker/aktoerer.js
- scripts/modules/fagsaker/index.js
Legge til endepunkt for å slette aktoer
> Melosys-2424 - slette aktoerer

- scripts/modules/fagsaker/aktoerer.js
- scripts/modules/fagsaker/kontaktopplysninger.js
- scripts/utils/mock-util.js
emulating server lookup on both saknummer and orgnr.
> MELOSYS-2419 fagsaker aktor fullmektig

- scripts/get-mock-server.js
- scripts/mock_api_server.js
- scripts/modules/fagsaker/fagsaker.js
- scripts/modules/fagsaker/sok.js
- scripts/modules/lovvalgsperioder.js
- scripts/modules/oppgaver/oppgaver.js
- scripts/modules/oppgaver/sok.js
- scripts/modules/opprinneligLovvalgsperiode.js
- scripts/modules/vilkar.js
- scripts/schema.js
- scripts/test/opprinneligLovvalgsperiode.js
Added new module and test "opprinneligLovvalgsPeriode". Updated get-mock-server, mock_api_server, and schema
> MELOSYS-2526 Opprinnelige Lovvalgsperioder.

- scripts/mock_api_server.js
Endret vedtak endepunkt til saksflyt/vedtak da backend må ha dette på plass, men blir ikke ferdig da det er MELOSYS-2087 som fikser dette
> Vedtak-endepunkt

- scripts/mock_api_server.js
- scripts/mockservers/get-mock-server.js
- scripts/modules/eessi.js
- scripts/test/eessi.js
Hører sammen med https://github.com/navikt/melosys-web/pull/609
> MELOSYS-2808 - Navneendringer i endepunkt for sed under arbeid.

- CONTRIBUTING.md
Vi tilføyer punkter og avstemmer med @abjolseth før ACK.
> Utkast til retningslinjer for bidrag

- scripts/mock-clients/helpers.js
Slår av proxy for at tester skal kunne kjøres på linux-image
> Devops - mock tester for linux

- .gitignore
- scripts/mock_api_server.js
- scripts/modules/dokumenter.js
Flertall er mer konsekvent med resten av api.
Dokumenttest.pdf har byttet navn til hoveddokument.pdf.
Til master da vi ønsker å legge ut avslag funksjonalitet fortest mulig.
> MELOSYS-2886 - Behandlingsresultater

- package.json
- scripts/katalog.js
- scripts/mock_api_server.js
- scripts/modules/dokumenter/docutils.js
- scripts/modules/dokumenter/opprett.js
- scripts/modules/dokumenter/pdf.js
- scripts/modules/dokumenter/utkast.js
- scripts/modules/fagsaker/aktoerer.js
- scripts/modules/fagsaker/kontaktopplysninger.js
- scripts/modules/organisasjoner.js
- scripts/modules/personer.js
- scripts/utils/mock-util.js
- scripts/utils/schemavalidator/schema-post-validator.js
Rename dokumenttypeKode => produserbartDokument
Ny mapping mellom produserbartDokument kode og pdf dokument.
> DEVOPS produserbare dokumenter

- scripts/mock_api_server.js
- scripts/modules/dokumenter/index.js
- scripts/modules/dokumenter/utkast.js
- scripts/utils/schemavalidator/index.js
- scripts/utils/schemavalidator/schema-get-validator.js
Reverts navikt/melosys-web-mock#263
> Revert "Melosys-3010 - Forhåndsvisning av sed"

- scripts/katalog.js
- scripts/mock_api_server.js
- scripts/modules/dokumenter/index.js
- scripts/modules/dokumenter/utkast.js
- scripts/modules/dokumenter/utkast/brev.js
- scripts/modules/dokumenter/utkast/sed.js
- scripts/utils/schemavalidator/index.js
- scripts/utils/schemavalidator/schema-get-validator.js
Var litt rask til å merge forrige PR (https://github.com/navikt/melosys-web-mock/pull/263). Har revertet fra SPRINT-36 og opprettet på nytt.
> MELOSYS-3010 - Endepunkt for å hente forhåndsvisning av SED

- package.json
- scripts/katalog.js
- scripts/mock_api_server.js
- scripts/modules/fagsaker/fagsaker.js
- scripts/modules/fagsaker/index.js
- Endrer henlegg-videresend fra put til post.
> Melosys-3266 - Videresend fritekst

- scripts/katalog.js
- scripts/mock_api_server.js
- scripts/modules/saksflyt/anmodningsperioder.js
- scripts/modules/saksflyt/index.js
Gjør bestilling av anmodningsperiode om til post for å kunne sende ved mottakerinstitusjon
frontend: https://github.com/navikt/melosys-web/pull/774
schema: https://github.com/navikt/melosys-schema/pull/106
> MELOSYS-3377 - Send mottakerinstitusjon ved bestilling av anmodningsperiode

- package.json
- scripts/modules/dokumenter/utkast/brev.js
- scripts/modules/fagsaker/aktoerer.js
- scripts/utils/schemavalidator/schema-get-validator.js
- scripts/utils/utils.js
Se også korresponderende PR for melosys-schema "DEVOPS JSON5"
> DEVOPS JSON5

- scripts/katalog.js
- scripts/mock_api_server.js
- scripts/modules/fagsaker/fagsaker.js
- scripts/modules/fagsaker/index.js
schema: https://github.com/navikt/melosys-schema/pull/113
> MELOSYS-3053 - henleggvideresend med mottakerinstitusjon

- scripts/katalog.js
- scripts/mock_api_server.js
- scripts/modules/saksflyt/index.js
- scripts/modules/saksflyt/vedtak.js
Legger til endepunkt for revurdering.
Er noen feil ved "npm run mock", men disse er ikke relatert til denne PRen.
> Melosys-3340 - revurder

- .dockerignore
- .github/workflows/build.yml
- .npmrc
- CONTRIBUTING.md
- Dockerfile
- mock.config.js
- package.json
- scripts/katalog.js
- scripts/mock-clients/mock-client.js
- scripts/modules/saksflyt/vedtak.js
- scripts/utils/server-info.js
Det må settes en token for å hente fra github packages. Den kan settes slik: https://help.github.com/en/github/managing-packages-with-github-packages/configuring-npm-for-use-with-github-packages#authenticating-to-github-packages
- Tester og publiserer et dockerimage av mocken til github packages
- Henter melosys schema fra github packages
- Legger til exitcode 1 for testene(npm run mock). Skulle helst sett at de var kjørt via f.eks. jest, men det er en litt større oppgave tror jeg.
> Melosys 3406 - actions

- scripts/katalog.js
- scripts/mock_api_server.js
- scripts/modules/fagsaker/index.js
- scripts/modules/fagsaker/opprett.js
- scripts/modules/oppgaver/index.js
- scripts/modules/oppgaver/sok.js
Legger til endepunkter:
- fagsaker-opprett
- oppgaver-sok
> MELOSYS-3328 - Opprett sak

- scripts/katalog.js
- scripts/mock_api_server.js
- scripts/modules/fagsaker/fagsaker.js
- scripts/modules/fagsaker/index.js
Nytt endepkt for å avslutte fagsak
> MELOSYS-3323 - søknad ikke yrkesaktiv

- scripts/katalog.js
- scripts/mock_api_server.js
- scripts/modules/behandlingsgrunnlag.js
- Navneendring: soknader -> behandlingsgrunnlag
> MELOSYS-3515 - Behandlingsgrunnlag

- scripts/katalog.js
- scripts/mock_api_server.js
- scripts/modules/saksflyt/index.js
- scripts/modules/saksflyt/unntaksperioder.js
⚠️ Tester vil feile inntil skjema er publisert ⚠️
> MELOSYS-3602 - Endre sakflyt-unntaksperioder-godkjenn til post

- package.json
- scripts/katalog.js
- scripts/mock_api_server.js
- scripts/modules/fagsaker/index.js
- scripts/modules/fagsaker/revurder.js
- scripts/modules/saksflyt/index.js
- scripts/modules/saksflyt/vedtak.js
- Endepunkt endret i backend
Schema: https://github.com/navikt/melosys-schema/pull/151
> MELOSYS-3692 - saksflyt/vedtak/revurder -> fagsaker/revurder

- package.json
- scripts/modules/vilkaar.js
- scripts/utils/mock-util.js
- Gi 400 ved POST av inngangsvilkaar, og server inngangsvilkaar i POST respons
Schema:
https://github.com/navikt/melosys-schema/pull/157
Trenger schema for å passere test.
> MELOSYS-3701 - Inngangsvilkaar

- scripts/katalog.js
- scripts/modules/behandlinger/behandling.js
- Endret katalognavn for behandlinger grunnet tester i melosys-schema som ikke ble kjørt
schema: https://github.com/navikt/melosys-schema/pull/173
> MELOSYS-2199 - behandlinger -> behandlinger-behandling

- package.json
- scripts/modules/dokumenter/docutils.js
- scripts/modules/dokumenter/utkast/brev.js
- scripts/modules/vilkaar.js
Ta i bruk kodeverk fra GitHub package registry her også. Her er registry allerede satt i både `.npmrc` og node-setup action, så da burde det ikke være noe stress. 😅
> Bytt til kodeverk fra GitHub package registry

- scripts/mock_api_server.js
- scripts/modules/featuretoggle/featuretoggle.js
- scripts/modules/featuretoggle/index.js
Setter default til true, så får man skru av features på egenhånd hvis man ønsker det.
> Legg til endepunkt for featuretoggle

- package.json
- scripts/katalog.js
- scripts/mock_api_server.js
- scripts/modules/trygdeavgift/beregning.js
- scripts/modules/trygdeavgift/grunnlag.js
- scripts/modules/trygdeavgift/index.js
- scripts/utils/schemavalidator/index.js
- scripts/utils/schemavalidator/schema-put-validator.js
Til https://github.com/navikt/melosys-web/pull/1090
> Melosys 4211

- package.json
Legger til [nodemon](https://github.com/remy/nodemon/), som restarter mocken ved filendringer. Dette gjør at man slipper å manuelt restarte mocken for hver endring, noe som kan stjele mye tid.
> Restart ved filendring

- .npmrc
- package-lock.json
- package.json
Fikk ikke kjørt `npm install` uten `@NAVIKT` taggen
> La til navikt som owner av registry i npmrc

- .github/workflows/build.yml
- scripts/mock_api_server.js
- scripts/utils/server-info.js
Dette ble fjernet for en stund siden fra melosys-api, men glemt å fjerne herfra.
> Fjerner serverinfo endepunkt

- package-lock.json
- package.json
- scripts/katalog.js
- scripts/mock_api_server.js
- scripts/modules/vilkaar.js
- scripts/utils/utils.js
Legger til endepunkt for overstyring av inngangsvilkår
> MELOSYS-4515 - Overstyre inngangsvilkår
